import { TemplateCategory } from "@prisma/client";
import type { InvitationTemplateLayout } from "@/types/invitation-template";

export type SystemInvitationTemplatePreset = {
  slug: string;
  name: string;
  category: TemplateCategory;
  layoutData: InvitationTemplateLayout;
};

export const SYSTEM_INVITATION_TEMPLATES: SystemInvitationTemplatePreset[] = [
  {
    slug: "standard-minimal-gold",
    name: "Standard Minimal Or",
    category: TemplateCategory.STANDARD,
    layoutData: {
      version: 1,
      canvas: {
        width: 4,
        height: 5,
        backgroundColor: "#111827",
        borderRadius: 30,
      },
      elements: [
        {
          id: "std_title",
          type: "text",
          content: "Invitation",
          x: 12,
          y: 13,
          width: 76,
          height: 13,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Great Vibes",
            fontSize: 10,
            color: "#FDE68A",
            fontWeight: 400,
            textAlign: "center",
            lineHeight: 1,
            letterSpacing: 0,
          },
        },
        {
          id: "std_name",
          type: "variable",
          content: "{{guest_name}}",
          x: 10,
          y: 43,
          width: 80,
          height: 11,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 4.3,
            color: "#FFFFFF",
            fontWeight: 800,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.02,
          },
        },
        {
          id: "std_table",
          type: "variable",
          content: "Table {{guest_table}}",
          x: 18,
          y: 61,
          width: 64,
          height: 8,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 3.1,
            color: "#D1D5DB",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.04,
          },
        },
        {
          id: "std_qr",
          type: "qrcode",
          x: 38,
          y: 70,
          width: 24,
          height: 19.2,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          fgColor: "#111827",
          bgColor: "#FFFFFF",
          eccLevel: "H",
          showLogo: true,
        },
        {
          id: "std_footer",
          type: "text",
          content: "YambiPass",
          x: 30,
          y: 86,
          width: 40,
          height: 5,
          rotation: 0,
          zIndex: 2,
          opacity: 0.72,
          style: {
            fontFamily: "Inter",
            fontSize: 2.2,
            color: "#FDE68A",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1,
            letterSpacing: 0.08,
          },
        },
      ],
    },
  },
  {
    slug: "mariage-script-ivoire",
    name: "Mariage Ivoire Script",
    category: TemplateCategory.WEDDING,
    layoutData: {
      version: 1,
      canvas: {
        width: 4,
        height: 5,
        backgroundColor: "#F8F1E7",
        borderRadius: 34,
      },
      elements: [
        {
          id: "wed_title",
          type: "text",
          content: "Nous avons l'honneur de vous inviter",
          x: 10,
          y: 16,
          width: 80,
          height: 8,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Courgette",
            fontSize: 3.8,
            color: "#7C2D12",
            fontWeight: 400,
            textAlign: "center",
            lineHeight: 1.15,
            letterSpacing: 0,
          },
        },
        {
          id: "wed_name",
          type: "variable",
          content: "{{guest_name}}",
          x: 8,
          y: 41,
          width: 84,
          height: 13,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Great Vibes",
            fontSize: 9.5,
            color: "#9A3412",
            fontWeight: 400,
            textAlign: "center",
            lineHeight: 1,
            letterSpacing: 0,
          },
        },
        {
          id: "wed_table",
          type: "variable",
          content: "{{guest_table}}",
          x: 25,
          y: 64,
          width: 50,
          height: 6,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 2.7,
            color: "#92400E",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.08,
          },
        },
        {
          id: "wed_qr",
          type: "qrcode",
          x: 38,
          y: 74,
          width: 24,
          height: 19.2,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          fgColor: "#7C2D12",
          bgColor: "#FFF7ED",
          eccLevel: "H",
          showLogo: true,
        },
      ],
    },
  },
  {
    slug: "soutenance-editorial-bleu",
    name: "Soutenance Editorial Bleu",
    category: TemplateCategory.DEFENSE,
    layoutData: {
      version: 1,
      canvas: {
        width: 4,
        height: 5,
        backgroundColor: "#F8FAFC",
        borderRadius: 18,
      },
      elements: [
        {
          id: "def_label",
          type: "text",
          content: "Soutenance academique",
          x: 9,
          y: 12,
          width: 82,
          height: 6,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 2.8,
            color: "#1D4ED8",
            fontWeight: 800,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.09,
          },
        },
        {
          id: "def_title",
          type: "text",
          content: "Invitation officielle",
          x: 10,
          y: 25,
          width: 80,
          height: 11,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Georgia",
            fontSize: 5.4,
            color: "#0F172A",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1.05,
            letterSpacing: 0,
          },
        },
        {
          id: "def_name",
          type: "variable",
          content: "{{guest_name}}",
          x: 10,
          y: 51,
          width: 80,
          height: 9,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 4.2,
            color: "#1E293B",
            fontWeight: 800,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0,
          },
        },
        {
          id: "def_table",
          type: "variable",
          content: "Acces: {{guest_table}}",
          x: 14,
          y: 68,
          width: 72,
          height: 7,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 2.9,
            color: "#475569",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.04,
          },
        },
        {
          id: "def_qr",
          type: "qrcode",
          x: 38,
          y: 78,
          width: 24,
          height: 19.2,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          fgColor: "#0F172A",
          bgColor: "#FFFFFF",
          eccLevel: "H",
          showLogo: true,
        },
      ],
    },
  },
  {
    slug: "gala-noir-champagne",
    name: "Gala Noir Champagne",
    category: TemplateCategory.GALA,
    layoutData: {
      version: 1,
      canvas: {
        width: 4,
        height: 5,
        backgroundColor: "#080808",
        borderRadius: 30,
      },
      elements: [
        {
          id: "gala_title",
          type: "text",
          content: "GALA",
          x: 18,
          y: 15,
          width: 64,
          height: 10,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Georgia",
            fontSize: 6.2,
            color: "#F5D06F",
            fontWeight: 700,
            textAlign: "center",
            lineHeight: 1,
            letterSpacing: 0.22,
          },
        },
        {
          id: "gala_name",
          type: "variable",
          content: "{{guest_name}}",
          x: 8,
          y: 43,
          width: 84,
          height: 12,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Courgette",
            fontSize: 5.3,
            color: "#FFFFFF",
            fontWeight: 400,
            textAlign: "center",
            lineHeight: 1.15,
            letterSpacing: 0,
          },
        },
        {
          id: "gala_table",
          type: "variable",
          content: "{{guest_table}}",
          x: 23,
          y: 68,
          width: 54,
          height: 7,
          rotation: 0,
          zIndex: 1,
          opacity: 1,
          style: {
            fontFamily: "Inter",
            fontSize: 2.8,
            color: "#FDE68A",
            fontWeight: 800,
            textAlign: "center",
            lineHeight: 1.1,
            letterSpacing: 0.08,
          },
        },
        {
          id: "gala_qr",
          type: "qrcode",
          x: 38,
          y: 78,
          width: 24,
          height: 19.2,
          rotation: 0,
          zIndex: 2,
          opacity: 1,
          fgColor: "#080808",
          bgColor: "#FDE68A",
          eccLevel: "H",
          showLogo: true,
        },
      ],
    },
  },
];
